### ISSUE TITLE
Colcon build error

### ISSUE THREAD

**Issue by wchuchnowski** [alsora/ros2-raspberrypi#1]
Hi,

When I building ROS2-raspberrypi on my machine (MacOS Mojave + Docker for Mac), I am getting an error. How to build ROS2 correctly?

Error:
----------------------------------------
Starting >>> ros_environment
Finished <<< rosidl_default_generators [11.7s]
Starting >>> builtin_interfaces
--- stderr: ros_environment
CMake Warning:
  Manually-specified variables were not used by the project:

    CURL_INCLUDE_DIR
    CURL_LIBRARY
    EIGEN3_INCLUDE_DIR
    Eigen3_DIR
    THIRDPARTY

---
Finished <<< ros_environment [6.03s]
Starting >>> rcl_interfaces
--- stderr: builtin_interfaces
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "3.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /root/ros2_ws/install/share/python_cmake_module/cmake/Modules/FindPythonExtra.cmake:130 (find_package)
  /root/ros2_ws/install/share/rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake:24 (find_package)
  /root/ros2_ws/install/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:38 (include)
  /root/ros2_ws/install/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:169 (ament_execute_extensions)
  CMakeLists.txt:18 (rosidl_generate_interfaces)

---
Failed   <<< builtin_interfaces	[ Exited with code 1 ]
--- stderr: rcl_interfaces
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "3.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /root/ros2_ws/install/share/python_cmake_module/cmake/Modules/FindPythonExtra.cmake:130 (find_package)
  /root/ros2_ws/install/share/rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake:24 (find_package)
  /root/ros2_ws/install/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:38 (include)
  /root/ros2_ws/install/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:169 (ament_execute_extensions)
  CMakeLists.txt:20 (rosidl_generate_interfaces)

---
Aborted  <<< rcl_interfaces

Summary: 91 packages finished [6min 9s]
  1 package failed: builtin_interfaces
  1 package aborted: rcl_interfaces
  11 packages had stderr output: builtin_interfaces connext_cmake_module rcl_interfaces rmw_connext_cpp rmw_connext_shared_cpp rmw_opensplice_cpp ros_environment rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rosidl_typesupport_opensplice_c rosidl_typesupport_opensplice_cpp
  80 packages not processed

**Comment by alsora** [comment]
Hi, thank you for pointing me the error!

I fixed it and I also corrected a couple of typos. I suggest you to pull the last commits and repeat again all the steps.

Let me know if it solves your issue!

**Comment by alsora** [comment]
Hi @wchuchnowski, I assume that you managed to crosscompile everything, so I will close this issue.
If you have any other troubles let me know.
